import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { EditorialBreadcrumb, EditorialHero, EditorialNext, EditorialShell, Picture } from "../editorial-components";

export const metadata: Metadata = {
  title: "The Bridal Guide: Choosing a Ring | Lab Grant Diamond",
  description: "A considered guide to choosing a diamond silhouette, finding a ring size and preparing for your proposal and wedding day.",
  alternates: { canonical: "/bridal-guide" },
  openGraph: { title: "The Bridal Guide | Lab Grant Diamond", description: "From the first ring to the wedding day, a considered guide for your own love story.", url: "/bridal-guide", images: ["/media/wedding-hero.webp"] },
};

export default function BridalGuide() {
  return <EditorialShell variant="theme-guide">
    <EditorialBreadcrumb name="Bridal guide" path="/bridal-guide" />
    <EditorialHero eyebrow="03 / THE BRIDAL GUIDE" title={<>A little closer<br /><em>to forever.</em></>} description="Every love story unfolds differently. Here is a place to begin choosing the ring, planning the moment and making it yours." image="wedding-hero" alt="A couple share a quiet moment before their wedding" href="#guide" action="EXPLORE THE GUIDE" position="center 35%" />
    <section className="editorial-statement"><div className="wrap"><p className="eyebrow">A CONSIDERED BEGINNING</p><span className="editorial-hairline" /><h2>Follow the feeling.<br /><em>Keep the details close.</em></h2><p>There is no single way to choose a ring or celebrate your promise. These simple considerations can help you make thoughtful decisions along the way.</p></div></section>
    <section id="guide" className="editorial-guide"><div className="wrap"><article className="editorial-guide-row"><Picture file="cut-oval" alt="Oval cut diamond with soft reflected light" /><div><span>01 / FIND THE SHAPE</span><h2>Begin with<br /><em>the silhouette.</em></h2><p>Notice the shapes they already wear. An oval has gentle length; a round cut feels familiar and timeless; an emerald cut has clean, quiet lines. The setting matters too: a pared back band keeps attention on the centre stone, while pavé adds a little more light.</p><Link className="editorial-dark-link" href="/engagement-rings">EXPLORE ENGAGEMENT RINGS <ArrowRight size={17} /></Link></div></article><article className="editorial-guide-row"><Picture file="solitaire" alt="Close view of The Solitaire engagement ring" /><div><span>02 / CONSIDER THE FIT</span><h2>Make room<br /><em>for every day.</em></h2><p>A ring should feel comfortable as well as beautiful. If you can, use a ring they already wear on the intended finger to help check the size. Finger size can change with temperature and time of day, so a professional measurement is the most dependable starting point.</p><p>On The Solitaire page, you can compare the listed metal and size options before adding a design to the preview bag.</p><Link className="editorial-dark-link" href="/product/solitaire-ring">VIEW THE SOLITAIRE <ArrowRight size={17} /></Link></div></article><article className="editorial-guide-row"><Picture file="wedding-vows" alt="Wedding couple sharing a moment at their ceremony" /><div><span>03 / MAKE IT YOURS</span><h2>For the question.<br /><em>For the vows.</em></h2><p>Choose a moment that reflects your relationship, whether it is shared quietly or surrounded by everyone you love. If you plan to wear a wedding band beside an engagement ring, consider how the two profiles sit together and how each feels on its own.</p><Link className="editorial-dark-link" href="/wedding-bands">EXPLORE WEDDING BANDS <ArrowRight size={17} /></Link></div></article></div></section>
    <section className="editorial-guide-faq"><div className="wrap"><div><p className="eyebrow">A FEW MORE THOUGHTS</p><h2>The details<br /><em>that matter.</em></h2></div><div><details><summary>What if I do not know their ring size?</summary><p>Check a ring they wear on the same finger, if possible, and use the ring-size guide on The Solitaire page as a starting point. A jeweller can provide a more accurate measurement.</p></details><details><summary>Which diamond cut should I choose?</summary><p>Start with the shapes they already gravitate toward. Our cut gallery explores oval, round, marquise and emerald silhouettes. The Solitaire currently features an oval centre stone.</p></details><details><summary>Can I buy a wedding band on this site?</summary><p>The wedding bands page is an editorial inspiration gallery. Individual band products are not currently listed.</p></details><details><summary>Is the bag a checkout?</summary><p>The bag on The Solitaire page is a design preview. It does not process an order or payment.</p></details></div></div></section>
    <EditorialNext eyebrow="WHEN YOU ARE READY" title={<>The one<br /><em>that says it all.</em></>} copy="Discover the details of The Solitaire and picture the moment it becomes part of your story." href="/product/solitaire-ring" action="EXPLORE THE SOLITAIRE" image="emotion-final" />
  </EditorialShell>;
}
